controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# config/routes.yaml

app_home:
    path: /
    controller: App\Controller\HomeController::index

generate_pdf_attestation:
    path: /session/{id}/generate-pdf/{stagiaireId?}
    controller: 'App\Controller\SessionController::generatePdf'



